# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '01:00'
      # UTC -03:00
      timezone: 'America/Sao_Paulo'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 1
    versioning-strategy: auto
    commit-message:
      prefix: 'chore'
      include: 'scope'
